name: Test Vanilla Docker Compose Build
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:


defaults:
   run:
    working-directory: ./

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6
      - name: Test Vanilla Docker Compose Build
        run: |
          bash ./.github/workflows/scripts/dockercompose-vanilla-test.sh
